name: Dummy project
on:
  push:
    branches:
      - "master"
    paths:
      - 'src/**'
jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out the repo
        uses: actions/checkout@v3
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Build website image
        run: |
          docker build --platform linux --tag normapm/dockerclientes:latest -f Dockerfile .
      - name: Publish website image
        run: |
          docker push normapm/dockerclientes:latest
